version: 2
jobs:
  build:
    branchs:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:10.14.2
    environment:
      SOURCE_BRANCH: master
      TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}	# 复用缓存
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            -  ~/.cache/yarn
      - deploy:
          name: Deploy
          command: |
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              yarn build
              yarn run deploy -r https://${GH_TOKEN}@github.com/teofpqy/teof-blog.git -b $TARGET_BRANCH

